### ISSUE TITLE
ObservableList's change not being listened to

### ISSUE THREAD

**Issue by hydroper** [dart-lang/observable#109]
# Minimal Reproduction

**pubspec.yaml:**

```yaml
name: observable_demo

dependencies:
  observable: ^0.24.0
```

Dart:

```dart
import 'package:observable/observable.dart';

void main() {
  var obs = ObservableList.from(["first value"]);
  obs.changes.listen(([value = ""]) {
    print(value);
  });
  obs[0] = "second valuee";
}
```

## Expected Behavior

Print:

```
second valuee
```

## Current Behavior

Prints nothing.
